### ISSUE TITLE
Add README file listing flake8 violations defined

### ISSUE THREAD

**Issue by peterjc** [keisheiled/flake8-implicit-str-concat#1]
I really like the idea of this plugin as a short term solution until black https://github.com/psf/black/issues/26 is fixed.

I would encourage you to add a README file including an example showing what the flake8 error code prefix you are using is (recommended three letter, three number format, e.g. ``ABC001`` to reduce the chance of duplicate codes between plugins). In your case, ``ISC`` as a prefix make sense to me.

**Comment by peterjc** [comment]
I see you are working on this in #2, and have included ``pip install flake8-implicit-str-concat`` which I forgot to suggest 👍

**Comment by peterjc** [comment]
I filed #3 on the wider issue of not using an alphanumeric flake8 violation code

**Comment by keisheiled** [comment]
now that #3 has landed, I'd love to see a PR with this added!
