### ISSUE TITLE
At https://pypi.org/project/flake8_implicit_str_concat/ the one-line summary is cut short:

### ISSUE THREAD

**Issue by keisheiled** [keisheiled/flake8-implicit-str-concat#11]
At https://pypi.org/project/flake8_implicit_str_concat/ the one-line summary is cut short:

![image](https://user-images.githubusercontent.com/1324225/69804100-7ddce400-11e6-11ea-9c7f-e8913bf0a40c.png)

https://github.com/takluyver/flit#usage says

> Make sure that foobar's docstring starts with a one-line summary of what the module is

So perhaps add a short one-liner on the first line?

_Originally posted by @hugovk in https://github.com/keisheiled/flake8-implicit-str-concat/pull/9/files_

**Comment by keisheiled** [comment]
@hugovk I think, now the scope has changed to encouraging either:

```python
# good
x = (
    "11111111111111111111111111111111111111"
    "22222222222222222222222222222222222222"
)

# good
x = "11112222"
```

over any of the following:
```python
# bad
x = (
    "11111111111111111111111111111111111111" \
    "22222222222222222222222222222222222222"
)

# bad
x = "11111111111111111111111111111111111111" \
    "22222222222222222222222222222222222222"

# bad
x = (
    "11111111111111111111111111111111111111" \
    + "22222222222222222222222222222222222222"
)

# bad
x = "11111111111111111111111111111111111111" \
    + "22222222222222222222222222222222222222"

# bad
x = "1111" "2222"

# bad
x = "1111" + "2222"
```

the one line summary should now be about "encouraging correct string literal concatenation, without redundant tokens"

not sure on the phrasing though

**Comment by hugovk** [comment]
Yes, the summary could be more general, and the full README/description gives more details. Perhaps something like:

> Flake8 plugin to encourage correct string literal concatenation

**Comment by keisheiled** [comment]
@hugovk @peterjc what do you think of https://github.com/keisheiled/flake8-implicit-str-concat/pull/13/files ?

**Comment by peterjc** [comment]
That's an improvement 👍

**Comment by hugovk** [comment]
Looks good!
