### ISSUE TITLE
Continuous integration testing

### ISSUE THREAD

**Issue by peterjc** [keisheiled/flake8-implicit-str-concat#14]
Are you open to using TravisCI, CircleCI or similar for continuous integration testing? e.g. check the code actually follows black style, and run some minimal test cases - maybe something like this:

https://github.com/peterjc/flake8-black/blob/v0.1.1/.travis.yml
https://github.com/peterjc/flake8-black/blob/v0.1.1/tests/run_tests.sh

or:

https://github.com/peterjc/flake8-rst-docstrings/blob/v0.0.12/.travis.yml
https://github.com/peterjc/flake8-rst-docstrings/blob/v0.0.12/tests/run_tests.sh

These just install flake8 and the plugin, then have a crude bash script to run a few examples with flake8 and do minimal checks of the output.

**Comment by keisheiled** [comment]
I'd prefer to use github actions

**Comment by keisheiled** [comment]
It should also run `mypy --strict` on the code

**Comment by peterjc** [comment]
I've not used github actions yet - seeing how you do that would be interesting.

**Comment by hugovk** [comment]
I've used GitHub Actions and can set something up later, or if you'd like to have a go, here's an example:

* https://github.com/hugovk/pypistats/actions
* https://github.com/hugovk/pypistats/tree/master/.github/workflows

**Comment by hugovk** [comment]
Please see PR #16.

**Comment by keisheiled** [comment]
fixed in #16
