### ISSUE TITLE
Commit setup.py to repo

### ISSUE THREAD

**Issue by ExplodingCabbage** [keisheiled/flake8-implicit-str-concat#21]
I think most Python packages do this, and it makes it easier for someone unfamiliar with flake8 plugins to see how exactly any of this actually magically integrates with flake8!

**Comment by hugovk** [comment]
This project uses `pyproject.toml` instead:

* https://github.com/keisheiled/flake8-implicit-str-concat/blob/master/pyproject.toml

Here's a timely new blog post about `pyproject.toml` from a Python core dev:

* https://snarky.ca/what-the-heck-is-pyproject-toml/

**Comment by ExplodingCabbage** [comment]
D'oh. When I downloaded the source from PyPI I saw a setup.py so I just assumed that it had been manually written and not committed. Sorry for the error.
