### ISSUE TITLE
Support banning implicit concatenation instead of mandating it

### ISSUE THREAD

**Issue by ExplodingCabbage** [keisheiled/flake8-implicit-str-concat#22]
Currently this repo mandates that concatenation of literals across lines should always be done implicitly.

I'd like to implement the *opposite* rule. My rationale is this: while I agree that breaking up long strings via implicit concatenation is slightly prettier (and saves a couple of columns), the mere existence of implicit concatenation in the language introduces a class of bugs involving using implicit concatenation *accidentally*, and I think the benefits from making those bugs impossible outweigh the prettiness gain.

The class of bugs I'm talking about is one that I suspect most experienced Python programmers have hit at some point or other: leaving out a comma when writing or reordering a long list/tuple/set, resulting in two elements being implicitly concatenated unintentionally:

```python
stuff = [
    'foo',
    'bar'
    'baz',
    'qux',
]
```

(In https://www.python.org/dev/peps/pep-3126/, Jason Orendorff is quoted giving this as an argument in favour of removing implicit concatenation from the language. That proposal was rejected - but there's still value in being able to effectively remove it from the language on a per-project basis via a linter.)

I suggest providing a rule that forbids implicit concatenation alongside the existing rule mandating it, and have the new one be disabled by default.

**Comment by keisheiled** [comment]
> This is a plugin for the Python code checking tool Flake8 to encourage correct string literal concatenation.

It is my view that explicit string concatenation is incorrect. black resolves such accidental line splitting with:

```python
stuff = [
    "foo",
    "bar" "baz",
    "qux",
]
```

flake8-implicit-str-concat will then recommend removing the redundant `" "`

**Comment by keisheiled** [comment]
@ExplodingCabbage you can ignore ISC003 and create a rule using:

```python
def _implicit(file_tokens: Iterable[tokenize.TokenInfo]) -> Iterable[_ERROR]:
    return (
        (
            *a.end,
            "ESC001 implicitly concatenated string literals"
            None,
        )
        for (a, b) in more_itertools.pairwise(file_tokens)
        if a.type == b.type == tokenize.STRING
    )
```

**Comment by keisheiled** [comment]
Perhaps it would be better to prohibit implicit str concatenation outside of a parenth form?

```python
stuff = [
    "foo",
    (
        "bar"
        "baz"
    ),
    "qux",
]
```
