### ISSUE TITLE
Bump version and release to PyPI

### ISSUE THREAD

**Issue by mondeja** [keisheiled/flake8-implicit-str-concat#25]
I'm getting next warning installing the library (v0.1.0):

```
flake8-implicit-str-concat 0.1.0 requires attrs~=19.3, but you'll have attrs 20.3.0 which is incompatible.
```

I supposes that the new version is not released in PyPI because this requirement has been fixed in #24.
Could you release it? Thanks

**Comment by keisheiled** [comment]
should be available here: https://pypi.org/project/flake8-implicit-str-concat/0.2.0/
