### ISSUE TITLE
Standard flake8 violation with prefix, e.g. ISC001

### ISSUE THREAD

**Issue by peterjc** [keisheiled/flake8-implicit-str-concat#3]
Looking at the code and confirming with a test, your plugin returns messages like this:

```
$ flake8 example.py
example.py:line:column implicit-str-concat implicitly concatenated string literals on one line
```

The flake8 select/ignore options assume an alpha-numeric naming prefix, here I would suggest ``ISC`` for implicit string concatenation for your plugin, thus ``ISC001`` for this message:

```
$ flake8 example.py
example.py:line:column ISC001 implicitly concatenated string literals on one line
```

(Update: Fixed consistent typo - was autocorrect fighting me again?)

**Comment by keisheiled** [comment]
@peterjc can you create a PR for this please?

**Comment by keisheiled** [comment]
@peterjc where is this prefix format documented?

**Comment by hugovk** [comment]
Here's some documentation:

* http://flake8.pycqa.org/en/2.5.5/warnings.html

Here's another Flake8 plugin which has its own `YTT` prefix:

* https://github.com/asottile/flake8-2020/

It's useful so you can do things like `flake8 --select YTT`.

**Comment by keisheiled** [comment]
@hugovk that's only for flake8 2, I only support flake8 3 which as far as I was aware dropped that limitation

**Comment by keisheiled** [comment]
`python3 -m flake8 --select implicit-str-concat` still works for me

**Comment by hugovk** [comment]
Right you are.

http://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html shows examples of using error codes.

It's maybe not essential but would make it easier to use.

**Comment by keisheiled** [comment]
@hugovk easier to use in what way? I could introduce `implicit-str-concat-oneline` and `implicit-str-concat-continuation` later and both would be selected by `python3 -m flake8 --select implicit-str-concat`

**Comment by hugovk** [comment]
Less typing, consistency with other plugins. But not a big deal :)

**Comment by peterjc** [comment]
Consistency with ``A123`` or the now recommended ``ABC123`` pattern will also help with third party tools like editors and IDEs which support flake8.

**Comment by keisheiled** [comment]
@peterjc those IDEs and editors should be updated to support the full gamut of error IDs supported by flake8

**Comment by peterjc** [comment]
Getting IDEs to adapt to ``ABC123`` as well as ``A123`` style which is a simple regex change has taken enough effort - complete free format is just making extra work for everyone. e.g. Doing summary statistics on a code base.

**Comment by keisheiled** [comment]
> or the now recommended `ABC123`

there's currently no recommendation only a note of consideration

**Comment by peterjc** [comment]
I've commented on the flake8 issue - I would much prefer the flake8 documentation were more explicit about recommending ``ABC123`` style (to the point that were it my choice I'd make anything else an error in flake8).

**Comment by peterjc** [comment]
See https://gitlab.com/pycqa/flake8/issues/597 following discussion on https://gitlab.com/pycqa/flake8/merge_requests/385 - an alphanumeric style is expected (although not necessarily as strict as ``ABC123`` that remains the suggestion).

**Comment by keisheiled** [comment]
@peterjc  https://github.com/keisheiled/flake8-implicit-str-concat/pull/7

I really strongly prefer readable error codes like eslint and pylint perhaps flake8 4 can use a more inclusive regex

**Comment by peterjc** [comment]
Personal taste in the end - and we clearly differ on this point - but best to confirm to the flake convention if writing a flake8 plugin.
